Lab 3
manfe513/racoons pull request #12
Opened 2023-09-28 14:34 UTC by alex078567

Предлагаю придерживаться такой структуры папок

2023-09-29 11:15 UTC, TreVogas approved these changes

2023-09-30 07:25 UTC, manfe513 requested changes

2023-09-30 07:25 UTC, manfe513 commented on creating_software/lab_3/src/Main.java
> +            if (userInput < 0) {
<= ?

2023-09-30 07:25 UTC, manfe513 commented on creating_software/lab_3/src/Main.java
> +        Scanner in = new Scanner(System.in);
Scanner in = new Scanner(System.in); 
можно вынести на уровень класса, чтобы не создавать в разных методах
не критично

2023-09-30 07:25 UTC, manfe513 commented on creating_software/lab_3/src/Main.java
> +            if (userInput < 0) {
<= ?

2023-09-30 07:25 UTC, manfe513 commented on creating_software/lab_3/src/Main.java
> +
тут что-то будем вызывать?
кажется программа сейчас ничего не делает при запуске

2023-10-01 15:34 UTC, alex078567 commented on creating_software/lab_3/src/Main.java
> +            if (userInput < 0) {
Необходимо, чтобы число было именно строго больше нуля.

2023-10-01 15:34 UTC, alex078567 commented on creating_software/lab_3/src/Main.java
> +            if (userInput < 0) {
Необходимо, чтобы число было именно строго больше нуля.

2023-10-01 15:35 UTC, alex078567 commented on creating_software/lab_3/src/Main.java
> +
Действительно, удалил пока что

2023-10-01 15:35 UTC, alex078567 commented on creating_software/lab_3/src/Main.java
> +        Scanner in = new Scanner(System.in);
Вынес Scanner на уровень класса

2023-10-02 18:31 UTC, manfe513 commented on creating_software/lab_3/src/Main.java
> +        Scanner in = new Scanner(System.in);
тут теперь создание экземпляра не требуется

2023-10-02 18:31 UTC, manfe513 approved these changes

2023-10-05 04:22 UTC, KuklinaAleksandra approved these changes

2023-10-05 11:41 UTC, merged