added multiplication, and default case
manfe513/racoons pull request #3
Opened 2023-02-15 12:19 UTC by alex078567

2023-02-15 12:25 UTC, manfe513 requested changes

2023-02-15 12:25 UTC, manfe513 commented on calc.py
> +        print('incorrect input, please try again')
может нам смтоит предусмотреть возможность повторного входа в меню? чтобы не пришлось перезапускать программу, а просто ввести другой оператор?

2023-02-15 12:26 UTC, alex078567 commented on calc.py
> +        print('incorrect input, please try again')
Хорошо, исправлю

2023-02-15 12:26 UTC, TreVogas commented on calc.py
> +        print('incorrect input, please try again')
можно в цикл засунуть главный код, и выходить при определенном символе.

2023-02-22 09:56 UTC, manfe513 approved these changes

2023-02-22 09:57 UTC, merged