div
manfe513/racoons pull request #5
Opened 2023-02-15 12:23 UTC by KuklinaAleksandra

2023-02-15 12:26 UTC, manfe513 requested changes

2023-02-15 12:26 UTC, manfe513 commented on calc.py
> -    case '+':
предлагаю сохранить возможножность сложения, а деление добавить рядом

2023-02-15 12:37 UTC, alex078567 approved these changes

2023-02-15 12:37 UTC, alex078567 commented on calc.py
> +print("result = ", c)
Отличная идея, оставляем

2023-02-15 12:41 UTC, manfe513 approved these changes

2023-02-15 12:43 UTC, TreVogas commented on calc.py
> +print("result = ", c)
Нужно проверить на деление 0

2023-02-22 09:53 UTC, manfe513 approved these changes

2023-02-22 09:53 UTC, merged